language: node_js
node_js:
    - "5"
env:
  - CXX=g++-4.8 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: truffle test
before_script:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc@2.2.7
  - npm install
  - testrpc > /dev/null & 